-- ============================================
-- USERS (20 test users)
-- Password for all: password123
-- BCrypt hash: $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS
-- ============================================

-- Clear existing data first (order matters due to foreign keys)
TRUNCATE rating_likes, favorites, ratings, media_genres, media, sessions, users RESTART IDENTITY CASCADE;

INSERT INTO users (username, password, email, favorite_genre_id) VALUES
                                                                     ('john_doe', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'john.doe@email.com', 1),
                                                                     ('jane_smith', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'jane.smith@email.com', 4),
                                                                     ('mike_wilson', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'mike.wilson@email.com', 9),
                                                                     ('emily_brown', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'emily.brown@email.com', 5),
                                                                     ('alex_jones', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'alex.jones@email.com', 6),
                                                                     ('sarah_davis', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'sarah.davis@email.com', 8),
                                                                     ('chris_miller', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'chris.miller@email.com', 10),
                                                                     ('lisa_garcia', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'lisa.garcia@email.com', 3),
                                                                     ('david_martinez', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'david.martinez@email.com', 1),
                                                                     ('amanda_taylor', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'amanda.taylor@email.com', 7),
                                                                     ('kevin_anderson', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'kevin.anderson@email.com', 2),
                                                                     ('rachel_thomas', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'rachel.thomas@email.com', 4),
                                                                     ('jason_jackson', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'jason.jackson@email.com', 9),
                                                                     ('nicole_white', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'nicole.white@email.com', 5),
                                                                     ('brian_harris', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'brian.harris@email.com', 11),
                                                                     ('stephanie_clark', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'stephanie.clark@email.com', 12),
                                                                     ('matthew_lewis', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'matthew.lewis@email.com', 6),
                                                                     ('jennifer_walker', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'jennifer.walker@email.com', 8),
                                                                     ('daniel_hall', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'daniel.hall@email.com', 10),
                                                                     ('ashley_young', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.SgN/jMmQMFBEZtWQyS', 'ashley.young@email.com', 3);

-- ============================================
-- MEDIA - MOVIES (15 movies)
-- ============================================

INSERT INTO media (title, description, media_type, release_year, age_restriction, creator_id) VALUES
                                                                                                  ('The Dark Knight Rises', 'Eight years after the Joker''s reign of anarchy, Batman is forced to return from his exile to save Gotham City from the brutal terrorist Bane.', 'movie', 2012, 13, 1),
                                                                                                  ('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a CEO''s mind.', 'movie', 2010, 13, 1),
                                                                                                  ('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'movie', 2014, 10, 2),
                                                                                                  ('The Matrix', 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.', 'movie', 1999, 16, 3),
                                                                                                  ('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 'movie', 1994, 18, 4),
                                                                                                  ('Forrest Gump', 'The story of a simple man who witnesses and influences several major historical events in 20th century America.', 'movie', 1994, 12, 5),
                                                                                                  ('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'movie', 1994, 16, 6),
                                                                                                  ('Fight Club', 'An insomniac office worker and a soap salesman build a global organization to help vent male aggression.', 'movie', 1999, 18, 7),
                                                                                                  ('The Lord of the Rings: The Fellowship of the Ring', 'A young hobbit must destroy a powerful ring to save Middle-earth from the Dark Lord Sauron.', 'movie', 2001, 12, 8),
                                                                                                  ('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'movie', 2000, 16, 9),
                                                                                                  ('Jurassic Park', 'A pragmatic paleontologist touring an almost complete theme park is tasked with protecting a couple of kids after a power failure.', 'movie', 1993, 12, 10),
                                                                                                  ('The Silence of the Lambs', 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 'movie', 1991, 18, 11),
                                                                                                  ('Schindler''s List', 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce.', 'movie', 1993, 16, 12),
                                                                                                  ('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his mob partners.', 'movie', 1990, 18, 13),
                                                                                                  ('Avatar', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 'movie', 2009, 12, 14);

-- ============================================
-- MEDIA - SERIES (15 series)
-- ============================================

INSERT INTO media (title, description, media_type, release_year, age_restriction, creator_id) VALUES
                                                                                                  ('Breaking Bad', 'A high school chemistry teacher diagnosed with lung cancer turns to manufacturing meth to secure his family''s future.', 'series', 2008, 18, 1),
                                                                                                  ('Game of Thrones', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.', 'series', 2011, 18, 2),
                                                                                                  ('Stranger Things', 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces to get him back.', 'series', 2016, 14, 3),
                                                                                                  ('The Office', 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.', 'series', 2005, 12, 4),
                                                                                                  ('Friends', 'Follows the personal and professional lives of six twenty to thirty year-olds living in Manhattan.', 'series', 1994, 12, 5),
                                                                                                  ('The Mandalorian', 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', 'series', 2019, 12, 6),
                                                                                                  ('Chernobyl', 'A dramatization of the true story of one of the worst man-made catastrophes in history.', 'series', 2019, 16, 7),
                                                                                                  ('The Witcher', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', 'series', 2019, 18, 8),
                                                                                                  ('Peaky Blinders', 'A gangster family epic set in 1900s England, centered on a gang who sew razor blades in the peaks of their caps.', 'series', 2013, 18, 9),
                                                                                                  ('The Crown', 'Follows the political rivalries and romance of Queen Elizabeth II''s reign and the events that shaped the second half of the 20th century.', 'series', 2016, 12, 10),
                                                                                                  ('Sherlock', 'A modern update finds the classic detective in 21st century London.', 'series', 2010, 14, 11),
                                                                                                  ('Dark', 'A family saga with a supernatural twist, set in a German town, where the disappearance of two children exposes complex relationships.', 'series', 2017, 16, 12),
                                                                                                  ('Westworld', 'Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite can be indulged.', 'series', 2016, 18, 13),
                                                                                                  ('The Boys', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', 'series', 2019, 18, 14),
                                                                                                  ('Narcos', 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.', 'series', 2015, 18, 15);

-- ============================================
-- MEDIA - GAMES (15 games)
-- ============================================

INSERT INTO media (title, description, media_type, release_year, age_restriction, creator_id) VALUES
                                                                                                  ('The Last of Us', 'A hardened survivor and a young girl must work together to survive in a post-apocalyptic United States.', 'game', 2013, 18, 1),
                                                                                                  ('Red Dead Redemption 2', 'America, 1899. Arthur Morgan must deal with the decline of the wild west while trying to survive against government forces.', 'game', 2018, 18, 2),
                                                                                                  ('God of War', 'After wiping out the gods of Mount Olympus, Kratos moves to the Norse realm where he and his son must confront Norse gods.', 'game', 2018, 17, 3),
                                                                                                  ('The Witcher 3: Wild Hunt', 'Geralt of Rivia sets out one last time to slay beasts, bargain with kings, and navigate a war-torn land.', 'game', 2015, 18, 4),
                                                                                                  ('Elden Ring', 'An action RPG set in the Lands Between, a realm ruled by demigods. Rise, Tarnished, and be guided by grace.', 'game', 2022, 16, 5),
                                                                                                  ('Minecraft', 'A sandbox game that allows players to build with a variety of different blocks in a 3D procedurally generated world.', 'game', 2011, 7, 6),
                                                                                                  ('Grand Theft Auto V', 'Three criminals attempt to commit heists while under pressure from a corrupt government agency.', 'game', 2013, 18, 7),
                                                                                                  ('Zelda: Breath of the Wild', 'Link awakens from a hundred-year slumber to defeat Calamity Ganon before it can destroy the kingdom of Hyrule.', 'game', 2017, 10, 8),
                                                                                                  ('Horizon Zero Dawn', 'In a post-apocalyptic world, Aloy must discover her origins while battling the machines that roam the land.', 'game', 2017, 16, 9),
                                                                                                  ('Ghost of Tsushima', 'Jin Sakai must protect his homeland during the first Mongol invasion of Japan in 1274.', 'game', 2020, 18, 10),
                                                                                                  ('Cyberpunk 2077', 'An open-world action-adventure set in Night City, a megalopolis obsessed with power, glamour and body modification.', 'game', 2020, 18, 11),
                                                                                                  ('Hollow Knight', 'A challenging 2D action-adventure set in a vast ruined kingdom of insects and heroes.', 'game', 2017, 10, 12),
                                                                                                  ('Hades', 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.', 'game', 2020, 12, 13),
                                                                                                  ('Sekiro: Shadows Die Twice', 'In the late 1500s, a shinobi must rescue his young lord and exact revenge on his enemies.', 'game', 2019, 18, 14),
                                                                                                  ('Portal 2', 'Trapped in an abandoned science facility, you must solve physics-based puzzles to escape with the help of a sarcastic AI.', 'game', 2011, 10, 15);

-- ============================================
-- MEDIA_GENRES (Assign genres to media)
-- ============================================

-- Movies genres
INSERT INTO media_genres (media_id, genre_id) VALUES
                                                  (1, 1), (1, 4), (1, 10),
                                                  (2, 1), (2, 9), (2, 10),
                                                  (3, 2), (3, 4), (3, 9),
                                                  (4, 1), (4, 9),
                                                  (5, 4), (5, 10),
                                                  (6, 4), (6, 8),
                                                  (7, 4),
                                                  (8, 4), (8, 10),
                                                  (9, 2), (9, 5),
                                                  (10, 1), (10, 4),
                                                  (11, 2), (11, 9), (11, 10),
                                                  (12, 6), (12, 10),
                                                  (13, 4), (13, 11),
                                                  (14, 4), (14, 10),
                                                  (15, 1), (15, 2), (15, 9);

-- Series genres
INSERT INTO media_genres (media_id, genre_id) VALUES
                                                  (16, 4), (16, 10),
                                                  (17, 1), (17, 4), (17, 5),
                                                  (18, 4), (18, 5), (18, 6),
                                                  (19, 3),
                                                  (20, 3), (20, 8),
                                                  (21, 1), (21, 2), (21, 9),
                                                  (22, 4), (22, 10),
                                                  (23, 1), (23, 2), (23, 5),
                                                  (24, 4), (24, 10),
                                                  (25, 4),
                                                  (26, 4), (26, 7), (26, 10),
                                                  (27, 4), (27, 7), (27, 9),
                                                  (28, 4), (28, 7), (28, 9),
                                                  (29, 1), (29, 3), (29, 4),
                                                  (30, 4), (30, 10);

-- Games genres
INSERT INTO media_genres (media_id, genre_id) VALUES
                                                  (31, 1), (31, 2), (31, 4),
                                                  (32, 1), (32, 2), (32, 12),
                                                  (33, 1), (33, 2), (33, 5),
                                                  (34, 1), (34, 2), (34, 5),
                                                  (35, 1), (35, 5),
                                                  (36, 2),
                                                  (37, 1), (37, 2), (37, 10),
                                                  (38, 1), (38, 2), (38, 5),
                                                  (39, 1), (39, 2), (39, 9),
                                                  (40, 1), (40, 2),
                                                  (41, 1), (41, 9),
                                                  (42, 1), (42, 2),
                                                  (43, 1), (43, 2), (43, 5),
                                                  (44, 1), (44, 2),
                                                  (45, 2), (45, 3), (45, 9);

-- ============================================
-- RATINGS (150+ ratings from various users)
-- ============================================

INSERT INTO ratings (media_id, user_id, stars, comment, comment_confirmed) VALUES
                                                                               (1, 2, 5, 'Absolutely incredible! Nolan outdid himself.', true),
                                                                               (1, 3, 4, 'Great movie but not as good as The Dark Knight.', true),
                                                                               (1, 5, 5, 'Bane is such a compelling villain.', true),
                                                                               (1, 7, 4, 'Epic conclusion to the trilogy.', false),
                                                                               (1, 10, 5, 'One of the best superhero movies ever made.', true),
                                                                               (2, 3, 5, 'Mind-bending masterpiece!', true),
                                                                               (2, 4, 5, 'The soundtrack alone is worth it.', true),
                                                                               (2, 6, 4, 'A bit confusing but amazing visuals.', true),
                                                                               (2, 8, 5, 'Christopher Nolan is a genius.', true),
                                                                               (2, 11, 5, 'Watched it 5 times, still finding new details.', true),
                                                                               (2, 14, 4, 'Great concept, great execution.', false),
                                                                               (3, 1, 5, 'Made me cry. Beautiful story about love and sacrifice.', true),
                                                                               (3, 4, 5, 'The docking scene had me on the edge of my seat!', true),
                                                                               (3, 6, 5, 'Hans Zimmer''s score is phenomenal.', true),
                                                                               (3, 9, 4, 'A bit long but worth every minute.', true),
                                                                               (3, 12, 5, 'Science fiction at its finest.', true),
                                                                               (4, 1, 5, 'Revolutionary film that changed cinema.', true),
                                                                               (4, 5, 5, 'Red pill or blue pill? Iconic!', true),
                                                                               (4, 8, 4, 'The action sequences are legendary.', true),
                                                                               (4, 11, 5, 'Philosophical and action-packed.', true),
                                                                               (4, 15, 5, 'Ahead of its time.', true),
                                                                               (5, 2, 5, 'Tarantino''s masterpiece. The dialogue is unmatched.', true),
                                                                               (5, 6, 4, 'Non-linear storytelling done right.', true),
                                                                               (5, 9, 5, 'Every scene is memorable.', true),
                                                                               (5, 13, 5, 'Classic that never gets old.', true),
                                                                               (5, 16, 4, 'Not for everyone but I loved it.', false),
                                                                               (6, 3, 5, 'Life is like a box of chocolates.', true),
                                                                               (6, 7, 5, 'Tom Hanks deserved that Oscar.', true),
                                                                               (6, 10, 5, 'Heartwarming and inspiring.', true),
                                                                               (6, 14, 4, 'Great performances all around.', true),
                                                                               (6, 18, 5, 'A feel-good movie that stands the test of time.', true),
                                                                               (7, 1, 5, 'The greatest movie ever made. Period.', true),
                                                                               (7, 4, 5, 'Hope is a good thing.', true),
                                                                               (7, 8, 5, 'Morgan Freeman''s narration is perfect.', true),
                                                                               (7, 12, 5, 'A masterpiece of storytelling.', true),
                                                                               (7, 16, 5, 'Everyone should watch this at least once.', true),
                                                                               (7, 19, 5, 'The ending is so satisfying.', true),
                                                                               (8, 2, 5, 'The first rule is... you know the rest.', true),
                                                                               (8, 5, 4, 'That twist blew my mind.', true),
                                                                               (8, 9, 5, 'Dark, funny, and thought-provoking.', true),
                                                                               (8, 13, 4, 'Brad Pitt was perfect for this role.', false),
                                                                               (8, 17, 5, 'A cult classic for a reason.', true),
                                                                               (9, 3, 5, 'The beginning of an epic journey.', true),
                                                                               (9, 6, 5, 'Best fantasy movie ever made.', true),
                                                                               (9, 10, 5, 'Peter Jackson created magic.', true),
                                                                               (9, 14, 5, 'The Shire scenes are so peaceful.', true),
                                                                               (9, 18, 4, 'A bit long but worth it.', true),
                                                                               (10, 1, 5, 'Are you not entertained?!', true),
                                                                               (10, 5, 5, 'Russell Crowe was born for this role.', true),
                                                                               (10, 8, 4, 'Epic in every sense of the word.', true),
                                                                               (10, 12, 5, 'The colosseum scenes are incredible.', true),
                                                                               (10, 16, 4, 'A revenge story done right.', false),
                                                                               (11, 2, 5, 'Spielberg at his finest. The dinosaurs still look real!', true),
                                                                               (11, 6, 5, 'Childhood nostalgia in a movie.', true),
                                                                               (11, 9, 4, 'The T-Rex scene is legendary.', true),
                                                                               (11, 13, 5, 'Life finds a way.', true),
                                                                               (11, 17, 5, 'Groundbreaking visual effects.', true),
                                                                               (12, 3, 5, 'Anthony Hopkins is terrifying and brilliant.', true),
                                                                               (12, 7, 5, 'Psychological horror at its best.', true),
                                                                               (12, 10, 4, 'The tension is unbearable.', true),
                                                                               (12, 14, 5, 'Quid pro quo, Clarice.', true),
                                                                               (12, 18, 4, 'A true classic of the genre.', false),
                                                                               (13, 1, 5, 'Powerful and devastating. A must-watch.', true),
                                                                               (13, 4, 5, 'Spielberg''s most important film.', true),
                                                                               (13, 8, 5, 'The girl in the red coat... unforgettable.', true),
                                                                               (13, 11, 5, 'History brought to life.', true),
                                                                               (13, 15, 5, 'Emotionally draining but essential cinema.', true),
                                                                               (14, 2, 5, 'Scorsese at the top of his game.', true),
                                                                               (14, 5, 5, 'The narration style is iconic.', true),
                                                                               (14, 9, 4, 'Joe Pesci steals every scene.', true),
                                                                               (14, 12, 5, 'Funny how? Like a clown?', true),
                                                                               (14, 16, 4, 'Best mob movie ever made.', false),
                                                                               (15, 3, 4, 'Visually stunning but story is predictable.', true),
                                                                               (15, 6, 5, 'Pandora is breathtaking.', true),
                                                                               (15, 10, 4, 'The world-building is incredible.', true),
                                                                               (15, 13, 3, 'Pretty but shallow.', true),
                                                                               (15, 17, 4, 'A technical achievement.', false);

-- Series ratings
INSERT INTO ratings (media_id, user_id, stars, comment, comment_confirmed) VALUES
                                                                               (16, 2, 5, 'The greatest TV show ever made. Walter White''s transformation is masterful.', true),
                                                                               (16, 4, 5, 'Say my name.', true),
                                                                               (16, 7, 5, 'Bryan Cranston deserved every Emmy.', true),
                                                                               (16, 11, 5, 'The finale was perfect.', true),
                                                                               (16, 15, 5, 'Science, yeah!', true),
                                                                               (16, 19, 5, 'Binge-watched the entire thing. No regrets.', true),
                                                                               (17, 1, 4, 'Amazing until season 8...', true),
                                                                               (17, 5, 5, 'The Red Wedding destroyed me.', true),
                                                                               (17, 8, 4, 'Great characters, rushed ending.', true),
                                                                               (17, 12, 3, 'Season 8 ruined it for me.', true),
                                                                               (17, 16, 5, 'Seasons 1-4 are peak television.', true),
                                                                               (17, 20, 4, 'Winter came... and left too quickly.', false),
                                                                               (18, 3, 5, 'Perfect 80s nostalgia!', true),
                                                                               (18, 6, 5, 'Eleven is such a great character.', true),
                                                                               (18, 10, 4, 'Season 1 was the best.', true),
                                                                               (18, 14, 5, 'The Duffer Brothers are geniuses.', true),
                                                                               (18, 18, 4, 'Great blend of horror and coming-of-age.', true),
                                                                               (19, 1, 5, 'That''s what she said!', true),
                                                                               (19, 4, 5, 'Michael Scott is the best character ever.', true),
                                                                               (19, 7, 5, 'Bears. Beets. Battlestar Galactica.', true),
                                                                               (19, 11, 5, 'I''ve rewatched it at least 10 times.', true),
                                                                               (19, 15, 4, 'The later seasons aren''t as good.', true),
                                                                               (19, 19, 5, 'Comfort show for life.', true),
                                                                               (20, 2, 5, 'We were on a break!', true),
                                                                               (20, 5, 4, 'Classic sitcom. A bit dated now.', true),
                                                                               (20, 9, 5, 'Chandler is hilarious.', true),
                                                                               (20, 13, 4, 'Good for background watching.', false),
                                                                               (20, 17, 5, 'The one where everyone cries at the finale.', true),
                                                                               (21, 3, 5, 'This is the way.', true),
                                                                               (21, 6, 5, 'Baby Yoda! Need I say more?', true),
                                                                               (21, 10, 5, 'Star Wars done right.', true),
                                                                               (21, 14, 4, 'Great action and world-building.', true),
                                                                               (21, 18, 5, 'Best thing to come out of Disney Star Wars.', true),
                                                                               (22, 1, 5, 'Haunting and perfectly executed.', true),
                                                                               (22, 4, 5, 'The attention to detail is incredible.', true),
                                                                               (22, 8, 5, 'Episode 4 is some of the best TV ever made.', true),
                                                                               (22, 11, 5, 'Terrifying because it''s real.', true),
                                                                               (22, 15, 5, 'A masterclass in tension.', true),
                                                                               (23, 2, 5, 'Toss a coin to your Witcher!', true),
                                                                               (23, 5, 4, 'Henry Cavill was born to play Geralt.', true),
                                                                               (23, 9, 4, 'Timeline is confusing at first.', true),
                                                                               (23, 12, 5, 'Great adaptation of the books and games.', true),
                                                                               (23, 16, 4, 'Action scenes are top-notch.', false),
                                                                               (24, 3, 5, 'By order of the Peaky Blinders!', true),
                                                                               (24, 6, 5, 'Cillian Murphy is phenomenal.', true),
                                                                               (24, 10, 5, 'Best soundtrack of any TV show.', true),
                                                                               (24, 13, 4, 'The cinematography is gorgeous.', true),
                                                                               (24, 17, 5, 'Arthur! Arthur! Arthur!', true),
                                                                               (25, 1, 4, 'Beautifully made. A bit slow at times.', true),
                                                                               (25, 4, 5, 'The acting is superb across all seasons.', true),
                                                                               (25, 8, 4, 'Fascinating look at the royal family.', true),
                                                                               (25, 11, 4, 'Each cast change is seamless.', false),
                                                                               (26, 2, 5, 'Benedict Cumberbatch IS Sherlock Holmes.', true),
                                                                               (26, 5, 5, 'The Reichenbach Fall is phenomenal.', true),
                                                                               (26, 9, 4, 'Season 4 wasn''t as strong.', true),
                                                                               (26, 12, 5, 'Clever writing and great chemistry.', true),
                                                                               (27, 3, 5, 'The most complex and rewarding show I''ve ever watched.', true),
                                                                               (27, 6, 5, 'German excellence. Mind-bending plot.', true),
                                                                               (27, 10, 5, 'Makes Inception look simple.', true),
                                                                               (27, 14, 4, 'Need a family tree to follow along!', true),
                                                                               (28, 1, 4, 'Season 1 is a masterpiece. Then...', true),
                                                                               (28, 4, 5, 'The maze was worth it.', true),
                                                                               (28, 8, 3, 'Got too convoluted after season 2.', true),
                                                                               (28, 11, 4, 'Great concept, mixed execution.', false),
                                                                               (29, 2, 5, 'Homelander is the scariest villain on TV.', true),
                                                                               (29, 5, 5, 'Superhero satire at its finest.', true),
                                                                               (29, 9, 5, 'Diabolical!', true),
                                                                               (29, 13, 4, 'Very violent but so good.', true),
                                                                               (29, 17, 5, 'Butcher is an amazing character.', true),
                                                                               (30, 3, 4, 'Wagner Moura was perfect as Escobar.', true),
                                                                               (30, 6, 5, 'Gripping from start to finish.', true),
                                                                               (30, 10, 4, 'Seasons 1-2 are the best.', true),
                                                                               (30, 14, 5, 'Fascinating true story.', false);

-- Game ratings
INSERT INTO ratings (media_id, user_id, stars, comment, comment_confirmed) VALUES
                                                                               (31, 1, 5, 'The greatest video game story ever told.', true),
                                                                               (31, 4, 5, 'Joel and Ellie''s relationship is beautiful.', true),
                                                                               (31, 7, 5, 'The giraffe scene...', true),
                                                                               (31, 11, 5, 'Naughty Dog outdid themselves.', true),
                                                                               (31, 15, 5, 'Made me cry multiple times.', true),
                                                                               (31, 19, 5, 'A masterpiece in interactive storytelling.', true),
                                                                               (32, 2, 5, 'Arthur Morgan is the best protagonist in gaming.', true),
                                                                               (32, 5, 5, 'The attention to detail is insane.', true),
                                                                               (32, 8, 5, 'I spent 200 hours and don''t regret a minute.', true),
                                                                               (32, 12, 5, 'That ending broke me.', true),
                                                                               (32, 16, 4, 'A bit slow at the start but worth it.', true),
                                                                               (32, 20, 5, 'Rockstar''s magnum opus.', true),
                                                                               (33, 3, 5, 'BOY!', true),
                                                                               (33, 6, 5, 'Kratos as a father is unexpectedly emotional.', true),
                                                                               (33, 10, 5, 'The one-shot camera is incredible.', true),
                                                                               (33, 14, 5, 'Best hack and slash ever made.', true),
                                                                               (33, 18, 5, 'That first boss fight set the tone.', true),
                                                                               (34, 1, 5, 'Gwent alone is worth the price.', true),
                                                                               (34, 4, 5, 'Best open world RPG ever made.', true),
                                                                               (34, 7, 5, 'Blood and Wine is the best DLC ever.', true),
                                                                               (34, 11, 5, 'Geralt is such a great character.', true),
                                                                               (34, 15, 5, 'Hundreds of hours and I still find new things.', true),
                                                                               (34, 19, 5, 'CDPR set the gold standard.', false),
                                                                               (35, 2, 5, 'Miyazaki and Martin created something special.', true),
                                                                               (35, 5, 5, 'Hardest but most rewarding game I''ve played.', true),
                                                                               (35, 9, 5, 'The open world suits the formula perfectly.', true),
                                                                               (35, 13, 4, 'Too hard for casual gamers but amazing.', true),
                                                                               (35, 17, 5, 'Game of the Year, no contest.', true),
                                                                               (36, 3, 5, 'Limitless creativity. A gaming phenomenon.', true),
                                                                               (36, 6, 5, 'I''ve been playing for 10 years and still love it.', true),
                                                                               (36, 10, 5, 'Perfect for any age.', true),
                                                                               (36, 14, 4, 'Simple concept, infinite possibilities.', true),
                                                                               (36, 18, 5, 'The best-selling game of all time for a reason.', true),
                                                                               (37, 1, 5, 'Los Santos is an incredible playground.', true),
                                                                               (37, 4, 5, 'Three protagonists was a genius idea.', true),
                                                                               (37, 8, 4, 'Story is good, online is where it shines.', true),
                                                                               (37, 12, 5, 'Rockstar knows how to make open worlds.', true),
                                                                               (37, 16, 4, 'Still waiting for GTA 6...', false),
                                                                               (38, 2, 5, 'Redefined open world games.', true),
                                                                               (38, 5, 5, 'Freedom like no other game.', true),
                                                                               (38, 9, 5, 'Nintendo magic at its finest.', true),
                                                                               (38, 13, 5, 'The physics system is amazing.', true),
                                                                               (38, 17, 5, 'A masterpiece that changed gaming.', true),
                                                                               (39, 3, 5, 'Robot dinosaurs! What more do you need?', true),
                                                                               (39, 6, 5, 'Aloy is a fantastic protagonist.', true),
                                                                               (39, 10, 4, 'Great combat, interesting lore.', true),
                                                                               (39, 14, 5, 'The story unravels beautifully.', true),
                                                                               (39, 18, 4, 'Beautiful world to explore.', true),
                                                                               (40, 1, 5, 'The most beautiful game ever made.', true),
                                                                               (40, 4, 5, 'Sucker Punch created a love letter to samurai films.', true),
                                                                               (40, 8, 5, 'Photo mode is incredible.', true),
                                                                               (40, 11, 5, 'Combat feels so satisfying.', true),
                                                                               (40, 15, 4, 'Open world activities can get repetitive.', false),
                                                                               (41, 2, 3, 'Great story, buggy launch.', true),
                                                                               (41, 5, 4, 'Much better after the patches.', true),
                                                                               (41, 9, 4, 'Night City is stunning.', true),
                                                                               (41, 12, 3, 'Potential not fully realized.', true),
                                                                               (41, 16, 4, 'Keanu Reeves was great.', true),
                                                                               (42, 3, 5, 'Best indie game I''ve ever played.', true),
                                                                               (42, 6, 5, 'The art style is gorgeous.', true),
                                                                               (42, 10, 5, 'So much content for the price.', true),
                                                                               (42, 14, 5, 'Challenging but fair.', true),
                                                                               (42, 18, 4, 'Silksong when?!', true),
                                                                               (43, 1, 5, 'Perfect roguelike. The story integration is genius.', true),
                                                                               (43, 4, 5, 'Every run feels different.', true),
                                                                               (43, 7, 5, 'Supergiant''s best game.', true),
                                                                               (43, 11, 5, 'The voice acting is superb.', true),
                                                                               (43, 15, 5, 'I can''t stop playing.', true),
                                                                               (44, 2, 5, 'Hesitation is defeat.', true),
                                                                               (44, 5, 5, 'Best combat system in gaming.', true),
                                                                               (44, 8, 5, 'FromSoftware at their finest.', true),
                                                                               (44, 12, 4, 'Harder than Dark Souls but more rewarding.', true),
                                                                               (44, 16, 5, 'That final boss...', false),
                                                                               (45, 3, 5, 'The cake is a lie!', true),
                                                                               (45, 6, 5, 'GLaDOS is the best villain.', true),
                                                                               (45, 9, 5, 'Puzzle design is flawless.', true),
                                                                               (45, 13, 5, 'Co-op mode is hilarious with friends.', true),
                                                                               (45, 17, 5, 'Valve peaked here. We need Portal 3.', true);

-- ============================================
-- FAVORITES
-- ============================================

INSERT INTO favorites (media_id, user_id) VALUES
                                              (1, 2), (1, 5), (1, 10),
                                              (2, 3), (2, 8), (2, 11),
                                              (3, 1), (3, 4), (3, 12),
                                              (7, 1), (7, 4), (7, 8), (7, 12), (7, 16), (7, 19),
                                              (9, 3), (9, 6), (9, 14), (9, 18),
                                              (16, 2), (16, 7), (16, 11), (16, 15), (16, 19),
                                              (17, 1), (17, 5), (17, 16),
                                              (19, 1), (19, 4), (19, 7), (19, 11), (19, 15), (19, 19),
                                              (22, 1), (22, 4), (22, 8), (22, 11), (22, 15),
                                              (31, 1), (31, 4), (31, 7), (31, 11), (31, 15), (31, 19),
                                              (32, 2), (32, 5), (32, 8), (32, 12), (32, 16), (32, 20),
                                              (34, 1), (34, 4), (34, 7), (34, 11), (34, 15), (34, 19),
                                              (38, 2), (38, 5), (38, 9), (38, 13), (38, 17);

-- ============================================
-- RATING LIKES
-- ============================================

INSERT INTO rating_likes (rating_id, user_id) VALUES
                                                  (1, 4), (1, 6), (1, 8),
                                                  (2, 1), (2, 5), (2, 9),
                                                  (6, 1), (6, 2), (6, 5), (6, 9), (6, 12),
                                                  (31, 2), (31, 3), (31, 5), (31, 6), (31, 7), (31, 9), (31, 10),
                                                  (66, 1), (66, 3), (66, 5),
                                                  (72, 2), (72, 4), (72, 6),
                                                  (84, 1), (84, 3), (84, 7), (84, 10),
                                                  (111, 2), (111, 3), (111, 5), (111, 6), (111, 8), (111, 9),
                                                  (117, 1), (117, 4), (117, 7), (117, 10);

